import { Product } from './types';

export const products: Product[] = [
  {
    id: 'achu-muruku-karam',
    name: 'Achu Muruku (Karam) Spicy',
    description: 'Traditional, crispy, and spicy rose cookies. Tradition in every bite, taste in every crunch!',
    price: 150,
    weight: '250g',
    image: '/images/products/achu-muruku-karam.jpg',
    category: 'Snacks',
    spiceLevel: 'Hot',
  },
  {
    id: 'sambar-podi',
    name: 'Sambar Podi',
    description: 'Traditional South Indian staple blend for everyday sambar.',
    price: 120,
    weight: '200g',
    image: '/images/products/sambar-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Medium',
    isBestseller: true,
  },
  {
    id: 'rasam-powder',
    name: 'Rasam Powder',
    description: 'Aromatic blend for authentic, comforting rasam.',
    price: 120,
    weight: '200g',
    image: '/images/products/rasam-powder.jpg',
    category: 'Masalas',
    spiceLevel: 'Medium',
  },
  {
    id: 'idly-milakaipodi',
    name: 'Idly Milakaipodi',
    description: 'Spicy lentil powder, the perfect accompaniment for idlies and dosas.',
    price: 130,
    weight: '200g',
    image: '/images/products/idly-milakaipodi.jpg',
    category: 'Masalas',
    spiceLevel: 'Hot',
  },
  {
    id: 'puliyodharai-podi',
    name: 'Puliyodharai Podi',
    description: 'Tangy tamarind rice mix for traditional festival flavors.',
    price: 140,
    weight: '200g',
    image: '/images/products/puliyodharai-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Medium',
  },
  {
    id: 'angayapodi',
    name: 'Angayapodi',
    description: 'Authentic spice blend for postpartum care and digestion.',
    price: 140,
    weight: '200g',
    image: '/images/products/angayapodi.jpg',
    category: 'Masalas',
    spiceLevel: 'Mild',
  },
  {
    id: 'health-mix',
    name: 'Health Mix',
    description: 'Nutrient-dense traditional mix for daily wellness.',
    price: 180,
    weight: '200g',
    image: '/images/products/health-mix.jpg',
    category: 'Masalas',
    spiceLevel: 'Mild',
  },
  {
    id: 'ellu-milakai-podi',
    name: 'Ellu Milakai Podi',
    description: 'A robust, aromatic blend of roasted sesame seeds and red chilies, perfect for pairing with hot rice and ghee.',
    price: 130,
    weight: '200g',
    image: '/images/products/ellu-milakai-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Medium',
  },
  {
    id: 'karamathu-podi',
    name: 'Karamathu Podi',
    description: 'A fiery, traditional spice mix designed to add an authentic South Indian kick to your daily meals.',
    price: 130,
    weight: '200g',
    image: '/images/products/karamathu-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Hot',
  },
  {
    id: 'vathakuzhambu-podi',
    name: 'Vathakuzhambu Podi',
    description: 'A perfectly balanced, tangy, and spicy blend crafted for making rich, classic South Indian stews.',
    price: 130,
    weight: '200g',
    image: '/images/products/vathakuzhambu-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Medium',
  },
  {
    id: 'murungai-podi',
    name: 'Murungai Podi',
    description: 'A nutrient-dense, earthy powder made from premium moringa leaves, offering both health benefits and traditional taste.',
    price: 130,
    weight: '200g',
    image: '/images/products/murungai-podi.jpg',
    category: 'Masalas',
    spiceLevel: 'Mild',
  }
];
